FROM node:10.12.0-alpine
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait wait
RUN chmod +x /wait
ENV NODE_ENV dev
RUN npm install && npm install -g mocha
ARG port=80
CMD /wait && mocha tests/unitTests.js --exit